# Generated by Django 2.1.7 on 2019-03-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('level', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=100)),
                ('hash', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
